OLED_ENABLE = yes
VIA_ENABLE = no
WPM_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RAW_ENABLE = yes
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware

# MCU name
MCU = RP2040

# Bootloader selection
BOOTLOADER = rp2040

WS2812_DRIVER = vendor
SERIAL_DRIVER = vendor

SPLIT_KEYBOARD = yes